/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Futurealiti (https://sketchfab.com/futurealiti)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sports-bike-a80259b859c842d5824c25c61e0fc421
Title: Sports Bike
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BikeModel(props) {
    const { nodes, materials } = useGLTF('/model/sports_bike.glb')
    return (
        <group scale={[35, 35, 35]} {...props} dispose={null}>
            <group scale={0.01}>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={8}>
                    <group position={[0.062, 0.201, 0.37]} rotation={[0, 0, Math.PI]} scale={0.001}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.carpaint_body_front004_chrome_0.geometry}
                            material={materials.chrome}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.carpaint_body_front004_chrome_0_1.geometry}
                            material={materials.chrome}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.carpaint_body_front004_chrome_0_2.geometry}
                            material={materials.chrome}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front_metal_rough_plus_0.geometry}
                        material={materials.metal_rough_plus}
                        position={[-0.024, 0.159, 0.21]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front001_carpaint_red_0.geometry}
                        material={materials.carpaint_red}
                        position={[-0.001, -0.266, 0.683]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front002_paintRed_0.geometry}
                        material={materials.paintRed}
                        position={[-0.007, -0.224, 0.381]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front003_tire_sw_0.geometry}
                        material={materials.tire_sw}
                        position={[0.001, -0.088, 0.305]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front005_plastic_rough_grey_0.geometry}
                        material={materials.plastic_rough_grey}
                        position={[0, -0.085, 0.716]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front006_brakes_0.geometry}
                        material={materials.brakes}
                        position={[0, -0.174, 0.304]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front007_metal_black_0.geometry}
                        material={materials.metal_black}
                        position={[0.009, -0.033, 0.515]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front008_chrome_0.geometry}
                        material={materials.chrome}
                        position={[-0.005, -0.296, 0.546]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front009_metal_rough_plus_0.geometry}
                        material={materials.metal_rough_plus}
                        position={[0.03, 0.422, 0.416]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front010_metal_frey_0.geometry}
                        material={materials.metal_frey}
                        position={[-0.012, -0.551, 0.457]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front011_plasticOrange_0.geometry}
                        material={materials.plasticOrange}
                        position={[-0.002, 0.277, 0.617]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front012_glass_clear_0.geometry}
                        material={materials.glass_clear}
                        position={[-0.002, 0.769, 0.851]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front013_leather_black_0.geometry}
                        material={materials.leather_black}
                        position={[0, 0.335, 0.834]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front014_chrome_0.geometry}
                        material={materials.chrome}
                        position={[0, -0.143, 0.802]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front015_glass_orange_0.geometry}
                        material={materials.glass_orange}
                        position={[0, 0.076, 0.697]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front016_glass_red_0.geometry}
                        material={materials.glass_red}
                        position={[0, 0.821, 0.885]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front017_paintGoldSemi_0.geometry}
                        material={materials.paintGoldSemi}
                        position={[-0.046, -0.03, 0.617]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front018_goldChrome_0.geometry}
                        material={materials.goldChrome}
                        position={[0, -0.651, 0.474]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front019_plasticBrown_0.geometry}
                        material={materials.plasticBrown}
                        position={[-0.117, -0.185, 0.859]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front020_metal_rough_0.geometry}
                        material={materials.metal_rough}
                        position={[-0.16, 0.505, 0.381]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front021_metal_blue_0.geometry}
                        material={materials.metal_blue}
                        position={[0, -0.451, 0.942]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front022_plastic_rough_grey_0.geometry}
                        material={materials.plastic_rough_grey}
                        position={[0.138, -0.366, 0.959]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front023_plasticRed_0.geometry}
                        material={materials.plasticRed}
                        position={[-0.168, -0.382, 0.956]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front024_plastic_rough_black_plus_0.geometry}
                        material={materials.plastic_rough_black_plus}
                        position={[-0.01, -0.17, 0.602]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front025_decals_0.geometry}
                        material={materials.decals}
                        position={[-0.007, -0.266, 0.796]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carpaint_body_front026_glass_clear_0.geometry}
                        material={materials.glass_clear}
                        position={[0, -0.721, 0.817]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.001}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/model/sports_bike.glb')