/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Amine (https://sketchfab.com/amine0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/covered-car-29f00df9e67a49a3b7e06abeaad480b7
Title: Covered Car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BikeCoverModel(props) {
  const { nodes, materials } = useGLTF('/model/covered_car.glb')
  return (
<group {...props} dispose={null}>
  <group scale={0.01}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.coveredCar__0.geometry}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    >
      <meshStandardMaterial
        attach="material"
        color="white"
        transparent
        opacity={0.7}
        roughness={0.1}
        metalness={0.3}
      />
    </mesh>
  </group>
</group>

  )
}

useGLTF.preload('/model/covered_car.glb')