/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: daelus (https://sketchfab.com/chrisaelus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/audi-a7-sportback-2018-55-tfsi-8a045bc6d5744992828026d7ff78c735
Title: Audi A7 Sportback 2018 55 TFSI
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CarModel(props) {
  const { nodes, materials } = useGLTF('/model/audi_a7_sportback_2018_55_tfsi.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.8, 1.023, 1.821]} rotation={[0, 0.006, 0]} scale={1.863}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_44.geometry}
          material={materials.Car_Paint_body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials.Car_Paint_body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials['Black_Carbon.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_47.geometry}
          material={materials['Black_Carbon.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_48.geometry}
          material={materials['Metal.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials['Window.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials['Black_Metal.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials['Carbon_Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials['Car_paint.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials['Plate_number.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials['Window.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials['Car_paint.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials['Reflector.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials['Indicator.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials['LED_IGHT_2.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials['LED_LIGHT.017']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_60.geometry}
          material={materials.Laser}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials['Rear_Light.007']}
        />
      </group>
      <group position={[-0.431, 1.228, 1.785]} rotation={[0, 0.006, 0]} scale={1.863}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials['Car_ruuber_ture.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials['Carbon_Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials['Less_roughness_metal.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials['LED_SCREEN.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials['carb0n_grey.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_68.geometry}
          material={materials['Black_Carbon.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_69.geometry}
          material={materials['Aircons.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_70.geometry}
          material={materials['Black_Carbon.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71.geometry}
          material={materials['Car_paint.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_72.geometry}
          material={materials['Carbon_2.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73.geometry}
          material={materials['Metal.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_74.geometry}
          material={materials['Rims.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_75.geometry}
          material={materials['Main_LED_screen.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_76.geometry}
          material={materials['Leather.001']}
        />
      </group>
      <group position={[0.588, 0.536, -0.665]} rotation={[0, 0.006, 0]} scale={1.863}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_156.geometry}
          material={materials['Car_ruuber_ture.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_157.geometry}
          material={materials['Rims.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_158.geometry}
          material={materials['Rim_2.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_159.geometry}
          material={materials['Metal.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_160.geometry}
          material={materials['Black_Carbon.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_161.geometry}
          material={materials['Brake_motor.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_162.geometry}
          material={materials['Brake_motor.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_163.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[-2.195, 0.536, -0.649]} rotation={[0, 0.006, 0]} scale={1.863}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_165.geometry}
          material={materials['Car_ruuber_ture.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_166.geometry}
          material={materials['Rims.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_167.geometry}
          material={materials['Rim_2.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_168.geometry}
          material={materials['Metal.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_169.geometry}
          material={materials['Black_Carbon.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_170.geometry}
          material={materials['Brake_motor.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_171.geometry}
          material={materials['Brake_motor.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_172.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[0.605, 0.536, 3.819]} scale={1.863}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_174.geometry}
          material={materials['Car_ruuber_ture.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_175.geometry}
          material={materials['Rims.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_176.geometry}
          material={materials['Rim_2.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_177.geometry}
          material={materials['Metal.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_178.geometry}
          material={materials['Black_Carbon.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_179.geometry}
          material={materials['Brake_motor.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_180.geometry}
          material={materials['Brake_motor.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_181.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[-2.16, 0.536, 3.735]} scale={1.863}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_183.geometry}
          material={materials['Car_ruuber_ture.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_184.geometry}
          material={materials['Rims.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_185.geometry}
          material={materials['Rim_2.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_186.geometry}
          material={materials['Metal.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_187.geometry}
          material={materials['Black_Carbon.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_188.geometry}
          material={materials['Brake_motor.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_189.geometry}
          material={materials['Brake_motor.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_190.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Mirror.002']}
        position={[0.66, 1.523, 2.292]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Mirror.002']}
        position={[-0.8, 1.023, 1.821]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['LED_LIGHT.015']}
        position={[0.281, 1.059, 4.691]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials['LED_LIGHT.014']}
        position={[0.497, 1.118, 4.5]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['LED_LIGHT.007']}
        position={[0.461, 1.116, 4.536]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['LED_LIGHT.004']}
        position={[0.405, 1.074, 4.607]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials['LED_LIGHT.005']}
        position={[0.363, 1.07, 4.619]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['LED_LIGHT.006']}
        position={[0.32, 1.064, 4.654]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials['LED_LIGHT.008']}
        position={[0.24, 1.053, 4.726]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials['LED_LIGHT.009']}
        position={[0.198, 1.052, 4.76]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials['LED_LIGHT.010']}
        position={[0.158, 1.057, 4.792]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials['LED_LIGHT.011']}
        position={[0.11, 1.061, 4.827]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials['LED_LIGHT.012']}
        position={[0.05, 1.06, 4.85]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials['LED_LIGHT.013']}
        position={[0.019, 1.073, 4.85]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Tail_Window}
        position={[-0.811, 1.279, -2.086]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.Orange}
        position={[-1.695, 1.255, -2.076]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.Hazard_Light}
        position={[-1.633, 1.296, -2.078]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.Reflector_Rear}
        position={[-0.8, 1.023, 1.821]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.Reflector_Rear}
        position={[-0.8, 1.023, 1.821]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.Orange}
        position={[0.016, 1.255, -2.088]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials.Hazard_Light}
        position={[0.007, 1.296, -2.078]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials['Back_Window.008']}
        position={[0.33, 1.323, -1.887]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials['Back_Window.056']}
        position={[0.298, 1.337, -1.938]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials['Back_Window.057']}
        position={[0.249, 1.337, -1.972]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials['Back_Window.058']}
        position={[0.197, 1.337, -2.002]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials['LED_LIGHT.015']}
        position={[-1.819, 1.059, 4.701]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials['LED_LIGHT.014']}
        position={[-2.035, 1.118, 4.51]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials['LED_LIGHT.007']}
        position={[-1.999, 1.116, 4.546]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials['LED_LIGHT.004']}
        position={[-1.943, 1.074, 4.617]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials['LED_LIGHT.005']}
        position={[-1.901, 1.07, 4.629]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials['LED_LIGHT.006']}
        position={[-1.859, 1.064, 4.663]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials['LED_LIGHT.008']}
        position={[-1.778, 1.053, 4.735]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials['LED_LIGHT.009']}
        position={[-1.736, 1.052, 4.77]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials['LED_LIGHT.010']}
        position={[-1.696, 1.057, 4.802]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials['LED_LIGHT.011']}
        position={[-1.648, 1.061, 4.837]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials['LED_LIGHT.012']}
        position={[-1.589, 1.06, 4.859]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials['LED_LIGHT.013']}
        position={[-1.557, 1.073, 4.859]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials['Back_Window.059']}
        position={[0.145, 1.337, -2.029]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials['Back_Window.060']}
        position={[0.094, 1.336, -2.05]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        material={materials['Back_Window.061']}
        position={[0.026, 1.334, -2.069]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_118.geometry}
        material={materials['Back_Window.062']}
        position={[-0.029, 1.333, -2.08]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        material={materials['Back_Window.063']}
        position={[-0.085, 1.332, -2.096]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_122.geometry}
        material={materials['Back_Window.064']}
        position={[-0.142, 1.329, -2.11]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_124.geometry}
        material={materials['Back_Window.065']}
        position={[-0.204, 1.329, -2.119]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_126.geometry}
        material={materials['Back_Window.008']}
        position={[-1.962, 1.323, -1.88]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_128.geometry}
        material={materials['Back_Window.056']}
        position={[-1.93, 1.337, -1.931]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        material={materials['Back_Window.057']}
        position={[-1.88, 1.337, -1.965]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_132.geometry}
        material={materials['Back_Window.058']}
        position={[-1.829, 1.337, -1.995]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_134.geometry}
        material={materials['Back_Window.059']}
        position={[-1.777, 1.337, -2.022]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        material={materials['Back_Window.060']}
        position={[-1.726, 1.336, -2.043]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials['Back_Window.061']}
        position={[-1.657, 1.334, -2.061]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials['Back_Window.062']}
        position={[-1.603, 1.333, -2.073]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials['Back_Window.063']}
        position={[-1.547, 1.332, -2.089]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials['Back_Window.064']}
        position={[-1.49, 1.329, -2.103]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        material={materials['Back_Window.065']}
        position={[-1.427, 1.329, -2.112]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        material={materials['Back_Window.066']}
        position={[-1.374, 1.327, -2.12]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        material={materials['Back_Window.067']}
        position={[-1.316, 1.326, -2.131]}
        rotation={[0, 0.006, 0]}
        scale={1.863}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials['Back_Window.066']}
        position={[-0.257, 1.327, -2.127]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials['Back_Window.067']}
        position={[-0.316, 1.326, -2.139]}
        rotation={[0, -0.006, 0]}
        scale={[-1.863, 1.863, 1.863]}
      />
    </group>
  )
}

useGLTF.preload('/model/audi_a7_sportback_2018_55_tfsi.glb')